"""empty message

Revision ID: 1eeac39f1bc3
Revises: 0f1a17fd841e
Create Date: 2020-01-18 17:02:04.449770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eeac39f1bc3'
down_revision = '0f1a17fd841e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_rows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_rows',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='test_rows_pkey')
    )
    # ### end Alembic commands ###
